vscode:
  extensions:
    - timonwong.shellcheck@0.10.1:J9QwQEqo5+bxqMMZDnFUNQ==
    - mads-hartmann.bash-ide-vscode@1.11.0:VLESO/tPCjrfzzLcJy83aQ==
    - foxundermoon.shell-format@7.0.1:dJqOSN173jVh12b+ScTqtw==